[notion]
api_key = "your_notion_api_key_here"
database_id = "your_books_database_id_here"

[cloudinary]
cloud_name = "your_cloudinary_cloud_name"
api_key = "your_cloudinary_api_key"
api_secret = "your_cloudinary_api_secret"